@host=http://localhost:5190

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NWI5NTQ3YS05YWFkLTQxNTctOWFhZC0wNGM4MGE0YTk0YjYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYmVmMzcyYWQtYjFiZi00YmU2LWIwMzctNTVkNDVlNWNkYjgxIiwiZXhwIjoxNzAyNDM5OTUyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.GvaaA8GyBBK7Zn3GW92blU_0ATQ6XIQHPyrM3pu9VbI
